# Generated by Django 5.2.8 on 2025-11-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='telegram_notifications',
            new_name='telegram_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
