# Generated by Django 5.2.8 on 2025-11-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_telegram_notifications_userprofile_telegram_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='telegram_verified',
            new_name='telegram_connected',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='telegram_chat_id',
            new_name='telegram_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_verification_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_auth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
